language: node_js
node_js:
  - "12"
os:
  - linux
  - osx
  - windows
before_script:
  - npx prettier --write .
  - npm run build
  - npm start &
  - node testing-files/perfectThing.js &
  - sleep 2
after_script:
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then npm run windows_stop; fi
